# Generated by Django 4.1.13 on 2024-03-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_app', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('person_image', models.TextField()),
                ('cloth_image', models.TextField()),
                ('tryon_image', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
